services:
  mariadb:
    image: mariadb:11.4
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASS}
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: tvwallaushop/backend:local
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - ./backend.env
    environment:
      DB_HOST: mariadb
      DB_PORT: ${DB_PORT}
      AI_PY_SERVICE_URL: http://python-ai-service:8000
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    command: ["sh", "-c", "cd backend && npm run migrate && npm run start"]
    ports:
      - "${BACKEND_PORT}:3000"

  db-init:
    image: tvwallaushop/backend:local
    profiles: ["init"]
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - ./backend.env
    environment:
      DB_HOST: mariadb
      DB_PORT: ${DB_PORT}
      AI_PY_SERVICE_URL: http://python-ai-service:8000
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    command: ["sh", "-c", "cd backend && npm run migrate && npm run seed"]

  python-ai-service:
    image: tvwallaushop/python-ai-service:local
    ports:
      - "${PYTHON_PORT}:8000"

  frontend:
    image: tvwallaushop/frontend:local
    ports:
      - "${FRONTEND_PORT}:80"

volumes:
  mariadb_data:
